# Generated by Django 6.1.1 on 2026-09-12 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('place_type', models.CharField(max_length=100, verbose_name='Тип місця')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локація')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('session_id', models.CharField(max_length=255, verbose_name='Ідентифікатор сесії')),
            ],
        ),
    ]
